"""add service_type to services

Revision ID: 6a5f59806e0d
Revises: 97cd086d133c
Create Date: 2026-03-08 02:33:13.681474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5f59806e0d'
down_revision = '97cd086d133c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), server_default='song', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
