"""add is_admin to user

Revision ID: 7f5d06b1779c
Revises: 9adbffb7a5e4
Create Date: 2026-03-17 00:06:18.219901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5d06b1779c'
down_revision = '9adbffb7a5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('live2s', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('lives', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('lives', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('live2s', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
