"""add birth year to birthday

Revision ID: 98fcd4c66de9
Revises: 51a774b158e8
Create Date: 2026-02-20 23:02:50.494969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fcd4c66de9'
down_revision = '51a774b158e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
