"""add bible

Revision ID: 9adbffb7a5e4
Revises: 6a5f59806e0d
Create Date: 2026-03-14 22:19:27.255672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adbffb7a5e4'
down_revision = '6a5f59806e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse', sa.String(length=255), nullable=True),
    sa.Column('translation', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bibles')
    # ### end Alembic commands ###
